### ISSUE TITLE
Server crashes with trade

### ISSUE THREAD

**Issue by dginovker** [dginovker/2006rebotted#14]
```
java.io.IOException: No such file or directory                                                                                                                                 
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)                                                                                               
        at java.base/java.io.File.createNewFile(File.java:1024)                                                                                                                
        at redone.util.GameLogger.writeLog(GameLogger.java:97)                                                                                                                 
        at redone.game.players.Trading.giveItems(Trading.java:511)                                                                                                             
        at redone.net.packets.impl.ClickingButtons.processPacket(ClickingButtons.java:2506)                                                                                    
        at redone.net.packets.PacketHandler.processPacket(PacketHandler.java:166)                                                                                              
        at redone.game.players.Client.processQueuedPackets(Client.java:1135)                                                                                                   
        at redone.game.players.PlayerHandler.process(PlayerHandler.java:162)                                                                                                   
        at redone.Server.main(Server.java:156)   
```

Caught stacktrace

**Comment by benmaher95** [comment]
I think this was caused by an anomoly when I attempted a trade, haven't been able to replicate since.

**Comment by Gptaqbc** [comment]
@benmaher95  What happened exactly?

**Comment by Gptaqbc** [comment]
No more info about this or anything reported. I think we can close it.

**Comment by Gptaqbc** [comment]
@dginovker You can close this.
